<a href="https://colab.research.google.com/github/sandeepasandy/EDA-PROJECT/blob/main/EDA_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [4]:
data = pd.read_csv("/content/adult.csv")
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [5]:
#Understanding the Dataset
print(data.head())

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            13
1   50   Self-emp-not-inc         83311   Bachelors            13
2   38            Private        215646     HS-grad             9
3   53            Private        234721        11th             7
4   28            Private        338409   Bachelors            13

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   Capital Gain  capital loss  Hours per Week  Native Country  Income
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K

In [6]:
#understanding the dataset
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   Workclass       32561 non-null  object
 2   Final Weight    32561 non-null  int64
 3   Education       32561 non-null  object
 4   EducationNum    32561 non-null  int64
 5   Marital Status  32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Gender          32561 non-null  object
 10  Capital Gain    32561 non-null  int64
 11  capital loss    32561 non-null  int64
 12  Hours per Week  32561 non-null  int64
 13  Native Country  32561 non-null  object
 14  Income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None

In [7]:
#understanding the dataset
print(data.describe())

                Age  Final Weight  EducationNum  Capital Gain  capital loss  \
count  32561.000000  3.256100e+04  32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05     10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05      2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04      1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05      9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05     10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05     12.000000      0.000000      0.000000
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000

       Hours per Week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

In [8]:
#understanding the dataset
data.columns

Index(['Age', 'Workclass', 'Final Weight', 'Education', 'EducationNum',
       'Marital Status', 'Occupation', 'Relationship', 'Race', 'Gender',
       'Capital Gain', 'capital loss', 'Hours per Week', 'Native Country',
       'Income'],
      dtype='object')

In [9]:
#understanding the dataset
print(data.tail())

       Age      Workclass  Final Weight    Education  EducationNum  \
32556   27        Private        257302   Assoc-acdm            12
32557   40        Private        154374      HS-grad             9
32558   58        Private        151910      HS-grad             9
32559   22        Private        201490      HS-grad             9
32560   52   Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation Relationship    Race   Gender  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male
32558              Widowed        Adm-clerical    Unmarried   White   Female
32559        Never-married        Adm-clerical    Own-child   White     Male
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female

       Capital Gain  capital loss  Hours per Week  Native Country  Income
32556             0             0              38   United-States   <=50K
32557             0             0              40   United-States    >50K
32558             0             0              40   United-States   <=50K
32559             0             0              20   United-States   <=50K
32560         15024             0              40   United-States    >50K

In [10]:
#understanding the dataset
data.shape

(32561, 15)

In [11]:
#understanding the dataset
data.size

488415

In [12]:
#understanding the dataset
data.count()

Age               32561
Workclass         32561
Final Weight      32561
Education         32561
EducationNum      32561
Marital Status    32561
Occupation        32561
Relationship      32561
Race              32561
Gender            32561
Capital Gain      32561
capital loss      32561
Hours per Week    32561
Native Country    32561
Income            32561
dtype: int64

In [13]:
#1.Select and Display only the age column from the dataset.
data = pd.DataFrame(data)
print(data)
print(data["Age"])

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]
0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64

In [14]:
#2.select the age, education, occupation, and income columns
print(data[["Age","Education","Occupation","Income"]])

       Age    Education          Occupation  Income
0       39    Bachelors        Adm-clerical   <=50K
1       50    Bachelors     Exec-managerial   <=50K
2       38      HS-grad   Handlers-cleaners   <=50K
3       53         11th   Handlers-cleaners   <=50K
4       28    Bachelors      Prof-specialty   <=50K
...    ...          ...                 ...     ...
32556   27   Assoc-acdm        Tech-support   <=50K
32557   40      HS-grad   Machine-op-inspct    >50K
32558   58      HS-grad        Adm-clerical   <=50K
32559   22      HS-grad        Adm-clerical   <=50K
32560   52      HS-grad     Exec-managerial    >50K

[32561 rows x 4 columns]

In [15]:
#3.display the first 10 rows using iloc
print(data.iloc[10])

Age                                37
Workclass                     Private
Final Weight                   280464
Education                Some-college
EducationNum                       10
Marital Status     Married-civ-spouse
Occupation            Exec-managerial
Relationship                  Husband
Race                            Black
Gender                           Male
Capital Gain                        0
capital loss                        0
Hours per Week                     80
Native Country          United-States
Income                           >50K
Name: 10, dtype: object

In [16]:
#4.select rows 10 to 20 and display only the age and education columns
print(data.iloc[10:20][["Age","Education"]])

    Age      Education
10   37   Some-college
11   30      Bachelors
12   23      Bachelors
13   32     Assoc-acdm
14   40      Assoc-voc
15   34        7th-8th
16   25        HS-grad
17   32        HS-grad
18   38           11th
19   43        Masters

In [17]:
#5.filter and display all the people whose age is greater than 500
print(data["Age"] > 50)

0        False
1        False
2        False
3         True
4        False
         ...
32556    False
32557    False
32558     True
32559    False
32560     True
Name: Age, Length: 32561, dtype: bool

In [18]:
#6.filter and display all the people whose income is >50k
d=data["Income"]== ">50k"
print(d)

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Name: Income, Length: 32561, dtype: bool

In [19]:
#7.filter people whose age is greater than 40 and hours per week is greater than 20
d = (data["Age"] > 40) & (data["Hours per Week"] > 20)
print(d)

0        False
1        False
2        False
3         True
4        False
         ...
32556    False
32557    False
32558     True
32559    False
32560     True
Length: 32561, dtype: bool

In [20]:
#8.filter people whose education is either bachelors or masters using isin()
print(data[data["Education"].isin(["Bachelors", "Masters"])])

Empty DataFrame
Columns: [Age, Workclass, Final Weight, Education, EducationNum, Marital Status, Occupation, Relationship, Race, Gender, Capital Gain, capital loss, Hours per Week, Native Country, Income]
Index: []

In [21]:
#9.find the mean, median, minimum, and max age of people in the dataset
print(data["Age"].mean)
print(data["Age"].median)
print(data["Age"].min)
print(data["Age"].max)
#
print(data["Age"].agg(["mean", "median","min","max"]))

<bound method Series.mean of 0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64>
<bound method Series.median of 0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64>
<bound method Series.min of 0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64>
<bound method Series.max of 0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64>
mean      38.581647
median    37.000000
min       17.000000
max       90.000000
Name: Age, dtype: float64

In [ ]:
#10.find the standard deviation of age and hours-per-week
print(data[["Age", "Hours per Week"]].std())

Age               9.109615
Hours per Week    7.725394
dtype: float64

In [22]:
#11.use describe() to generate the statistical summary of all numerical columns
print(data.describe)

<bound method NDFrame.describe of        Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]>

In [61]:
#12. Number of unique education values and frequency of each education category
print("Unique Education Values:",
    data['Education'].nunique())
print(data['Education'].value_counts())

Unique Education Values: 16
Education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [63]:
# 13. Number of people in each income category
print(data['Income'].value_counts())

Income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [64]:
#14.Percentage of people in each income category
#percentage = (income_count / np.sum(income_count)) * 100
print(data['Income'].value_counts(normalize=True ) * 100)

Income
<=50K    75.919044
>50K     24.080956
Name: proportion, dtype: float64

In [65]:
# 15. Statistical analysis of hours-per-week for people earning >50K
print(data[data['Income'] == '>50K']
          ['Hours per Week'].agg(
          [
        'count',
        'mean',
        'median',
        'min',
        'max',
        'std'
    ]))

count     0.0
mean      NaN
median    NaN
min       NaN
max       NaN
std       NaN
Name: Hours per Week, dtype: float64

In [66]:
# 16. Statistical analysis of age for people with Bachelors education
print(data[data['Education'] == ' Bachelors']['Age'].agg(['count', 'mean', 'median', 'min', 'max', 'std']))

count     5355.000000
mean        38.904949
median      37.000000
min         19.000000
max         90.000000
std         11.912210
Name: Age, dtype: float64

In [67]:
# 17. Youngest and oldest persons
print(data['Age'].agg(['min','max']))

min    17
max    90
Name: Age, dtype: int64

In [68]:
# 18. Correlation between numerical columns
print(data.corr(numeric_only=True))

                   Age    Final Weight  EducationNum  Capital Gain  \
Age             1.000000   -0.076646      0.036527      0.077674
Final Weight   -0.076646    1.000000     -0.043195      0.000432
EducationNum    0.036527   -0.043195      1.000000      0.122630
Capital Gain    0.077674    0.000432      0.122630      1.000000
capital loss    0.057775   -0.010252      0.079923     -0.031615
Hours per Week  0.068756   -0.018768      0.148123      0.078409

                capital loss  Hours per Week
Age               0.057775       0.068756
Final Weight     -0.010252      -0.018768
EducationNum      0.079923       0.148123
Capital Gain     -0.031615       0.078409
capital loss      1.000000       0.054256
Hours per Week    0.054256       1.000000

In [69]:
# 19. Correlation between age and hours-per-week
print(data[['Age', 'Hours per Week']].corr())

                   Age    Hours per Week
Age             1.000000     0.068756
Hours per Week  0.068756     1.000000

In [70]:
# 20. Most common education and occupation
print( "Education Mode:",data['Education'].mode()[0])
print("Occupation Mode:",data['Occupation'].mode()[0])

Education Mode:  HS-grad
Occupation Mode:  Prof-specialty

In [23]:
# cleaning
# EDA-4 : Identify the NAN VALUES
# Data Cleaning-2 : Cleaning NULL values
# Approach -1 : Delete the record (row) or columns
# Approach -2.1 : Filling CONSTANT VALUES
# Approach -2.3 : Filling Mean
# median
# mode

In [24]:
#replacing null values which have question mark(?)
data = data.replace(" ?" ,None)

In [25]:
print(data.isna().sum())

Age                  0
Workclass         1836
Final Weight         0
Education            0
EducationNum         0
Marital Status       0
Occupation        1843
Relationship         0
Race                 0
Gender               0
Capital Gain         0
capital loss         0
Hours per Week       0
Native Country     583
Income               0
dtype: int64

In [26]:
#cleaning
#identify NaN Values
data.isna()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
#Filling CONSTANT VALUES
data['Workclass'] = data['Workclass'].fillna("Unknown")
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [77]:
#Filling Mean
data['Age'].mean()

np.float64(38.58164675532078)

In [78]:
#Filling Median
data['Age'].median()

37.0

In [82]:
#Filling Mode
data['Workclass'].fillna(data['Workclass'].mode()[0], inplace=True)

In [ ]:
#cleaning NULL Values
#data.dropna()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
#Delete the row or column
#data.dropna(axis=0)

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [28]:
#Backward Filling
data['Age']=data['Age'].bfill()
data['Hours per Week'] =data['Hours per Week'].bfill()
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [29]:
#Forward Filling
data['Age']=data['Age'].ffill()
data['Hours per Week'] =data['Hours per Week'].ffill()
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [30]:
#Interpolate:
data['Age']=data['Age'].interpolate()
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [31]:
#Detecting Outliers bounds(lower&upper)
Q1 = data['Age'].quantile(0.25)
Q3 = data['Age'].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound)
print(upper_bound)

-2.0
78.0

In [32]:
#Identify IQR outliers
iqr_outliers = data[
 (data['Age'] < lower_bound) |
 (data['Age'] > upper_bound)
]
print("IQR Outliers:",len(iqr_outliers))

IQR Outliers: 143

In [33]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from scipy.stats.mstats import winsorize

In [34]:
#Z-Score Method
data['Age_zscore'] = zscore(data['Age'])
z_outliers = data[
    data['Age_zscore'].abs()>3
]
print("Z-Score Outliers:",len(z_outliers))

Z-Score Outliers: 121

In [35]:
#Z-Score Trimming
data_trimmed = data[data['Age_zscore'].abs() <= 3]
print(data_trimmed)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income  Age_zscore
0       <=50K    0.030671
1       <=50K    0.837109
2       <=50K   -0.042642
3       <=50K    1.057047
4       <=50K   -0.775768
...       ...         ...
32556   <=50K   -0.849080
32557    >50K    0.103983
32558   <=50K    1.423610
32559   <=50K   -1.215643
32560    >50K    0.983734

[32440 rows x 16 columns]

In [36]:
#Winsorization
data['Age_winsorized'] = winsorize(
    data['Age'],
    limits=[0,0.3])
print(data.head())

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            13
1   45   Self-emp-not-inc         83311   Bachelors            13
2   38            Private        215646     HS-grad             9
3   45            Private        234721        11th             7
4   28            Private        338409   Bachelors            13

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   Capital Gain  capital loss  Hours per Week  Native Country  Income  \
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K

   Age_zscore  Age_winsorized
0    0.030671              39
1    0.837109              45
2   -0.042642              38
3    1.057047              45
4   -0.775768              28

In [37]:
#Outliers on Hours per week Column
#1.
Q1 = data['Hours per Week'].quantile(0.25)
Q3 = data['Hours per Week'].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound)
print(upper_bound)

32.5
52.5

In [38]:
#2.
iqr_outliers = data[
 (data['Hours per Week'] < lower_bound) |
 (data['Hours per Week'] > upper_bound)
]
print("IQR Outliers:",len(iqr_outliers))

IQR Outliers: 9008

In [39]:
#3.
#Z-Score Method
data['Hours per Week_zscore'] = zscore(data['Hours per Week'])
z_outliers = data[
    data['Hours per Week_zscore'].abs()>3
]
print("Z-Score Outliers:",len(z_outliers))

Z-Score Outliers: 440

In [40]:
#4.
#Z-Score Trimming
data_trimmed = data[data['Hours per Week_zscore'].abs() <= 3]
print(data_trimmed)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       45   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       45            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   45            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   45       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income  Age_zscore  Age_winsorized  Hours per Week_zscore
0       <=50K    0.030671              39              -0.035429
1       <=50K    0.837109              45              -2.222153
2       <=50K   -0.042642              38              -0.035429
3       <=50K    1.057047              45              -0.035429
4       <=50K   -0.775768              28              -0.035429
...       ...         ...             ...                    ...
32556   <=50K   -0.849080              27              -0.197409
32557    >50K    0.103983              40              -0.035429
32558   <=50K    1.423610              45              -0.035429
32559   <=50K   -1.215643              22              -1.655225
32560    >50K    0.983734              45              -0.035429

[32121 rows x 18 columns]

In [41]:
#5.Winsorization
data['Hours per Week_winsorized'] = winsorize(
    data['Hours per Week'],
    limits=[0,0.3])
print(data.head())

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            13
1   45   Self-emp-not-inc         83311   Bachelors            13
2   38            Private        215646     HS-grad             9
3   45            Private        234721        11th             7
4   28            Private        338409   Bachelors            13

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   Capital Gain  capital loss  Hours per Week  Native Country  Income  \
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K

   Age_zscore  Age_winsorized  Hours per Week_zscore  \
0    0.030671              39              -0.035429
1    0.837109              45              -2.222153
2   -0.042642              38              -0.035429
3    1.057047              45              -0.035429
4   -0.775768              28              -0.035429

   Hours per Week_winsorized
0                         40
1                         13
2                         40
3                         40
4                         40

In [42]:
#Outliers on Education Num
#1.
Q1 = data['EducationNum'].quantile(0.25)
Q3 = data['EducationNum'].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound)
print(upper_bound)

4.5
16.5

In [43]:
#2.
iqr_outliers = data[
 (data['EducationNum'] < lower_bound) |
 (data['EducationNum'] > upper_bound)
 ]
print("IQR Outliers:",len(iqr_outliers))

IQR Outliers: 1198

In [44]:
#3.
data['EducationNum_zscore'] = zscore(data['EducationNum'])
z_outliers = data[
    data['EducationNum_zscore'].abs()>3
]
print("Z-Score Outliers:",len(z_outliers))

Z-Score Outliers: 219

In [45]:
#4.
data_trimmed = data[data['EducationNum_zscore'].abs() <= 3]
print(data_trimmed)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       45   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       45            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   45            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   45       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income  Age_zscore  Age_winsorized  Hours per Week_zscore  \
0       <=50K    0.030671              39              -0.035429
1       <=50K    0.837109              45              -2.222153
2       <=50K   -0.042642              38              -0.035429
3       <=50K    1.057047              45              -0.035429
4       <=50K   -0.775768              28              -0.035429
...       ...         ...             ...                    ...
32556   <=50K   -0.849080              27              -0.197409
32557    >50K    0.103983              40              -0.035429
32558   <=50K    1.423610              45              -0.035429
32559   <=50K   -1.215643              22              -1.655225
32560    >50K    0.983734              45              -0.035429

       Hours per Week_winsorized  EducationNum_zscore
0                             40             1.134739
1                             13             1.134739
2                             40            -0.420060
3                             40            -1.197459
4                             40             1.134739
...                          ...                  ...
32556                         38             0.746039
32557                         40            -0.420060
32558                         40            -0.420060
32559                         20            -0.420060
32560                         40            -0.420060

[32342 rows x 20 columns]

In [46]:
#5.
data['EducationNum_winsorized'] = winsorize(
    data['EducationNum'],
    limits=[0,0.3])
print(data.head())

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            11
1   45   Self-emp-not-inc         83311   Bachelors            11
2   38            Private        215646     HS-grad             9
3   45            Private        234721        11th             7
4   28            Private        338409   Bachelors            11

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   ...  capital loss  Hours per Week  Native Country  Income Age_zscore  \
0  ...             0              40   United-States   <=50K   0.030671
1  ...             0              13   United-States   <=50K   0.837109
2  ...             0              40   United-States   <=50K  -0.042642
3  ...             0              40   United-States   <=50K   1.057047
4  ...             0              40            Cuba   <=50K  -0.775768

   Age_winsorized  Hours per Week_zscore  Hours per Week_winsorized  \
0              39              -0.035429                         40
1              45              -2.222153                         13
2              38              -0.035429                         40
3              45              -0.035429                         40
4              28              -0.035429                         40

   EducationNum_zscore  EducationNum_winsorized
0             1.134739                       11
1             1.134739                       11
2            -0.420060                        9
3            -1.197459                        7
4             1.134739                       11

[5 rows x 21 columns]

In [97]:
#Histogram
import seaborn as sns
import matplotlib.pyplot as plt
sns.histplot(data=data, x='Age', bins=20)
plt.title("Age Distribution")
plt.show()

In [92]:
# Scatter Plot
plt.scatter(data['Age'], data['Hours per Week'])
plt.title("Age vs Hours per Week")
plt.xlabel("Age")
plt.ylabel("Hours per Week")
plt.show()

In [93]:
#Box plot
sns.boxplot(data=data, x='Income', y='Age')
plt.title("Age Distribution by Income")
plt.show()

In [100]:
#Bar chart
data['Education'].value_counts().plot(kind='bar')
plt.title("Education Distribution")
plt.xlabel("Education")
plt.ylabel("Number of People")
plt.xticks(rotation=45)
plt.show()

In [101]:
#Count Plot
sns.countplot(data=data, x='Income')
plt.title("Income Distribution")
plt.show()

In [56]:
!pip install AutoViz

Collecting AutoViz
  Downloading autoviz-0.1.905-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from AutoViz) (2.0.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.13/dist-packages (from AutoViz) (1.9.6)
Collecting emoji (from AutoViz)
  Downloading emoji-2.16.0-py3-none-any.whl.metadata (5.7 kB)
Collecting pyamg (from AutoViz)
  Downloading pyamg-5.3.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from AutoViz) (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from AutoViz) (0.15.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from AutoViz) (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.13/dist-packages (from AutoViz) (0.19.0)
Collecting xgboost<1.7,>=0.82 (from AutoViz)
  Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (2025.12.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (4.16.0)
Collecting pandas-dq>=1.29 (from AutoViz)
  Downloading pandas_dq-1.29-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (2.1.3)
Collecting hvplot>=0.9.2 (from AutoViz)
  Downloading hvplot-0.12.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (1.23.2)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (1.9.4)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (2.2.3)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.13/dist-packages (from AutoViz) (0.13.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (3.8.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (3.2.1)
Requirement already satisfied: narwhals>=2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (2.26.0)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.16.0->AutoViz) (3.0.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from hvplot>=0.9.2->AutoViz) (26.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>3.7.4->AutoViz) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->AutoViz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->AutoViz) (2026.4)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (2.2.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (3.10.3)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (0.3.7)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (0.14.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from panel>=1.4.0->AutoViz) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->AutoViz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->AutoViz) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->AutoViz) (3.7.0)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->AutoViz) (8.5.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->AutoViz) (2025.11.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->AutoViz) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->AutoViz) (1.2.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->AutoViz) (3.1.6)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->AutoViz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->AutoViz) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->AutoViz) (2026.9.1)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->AutoViz) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->AutoViz) (2.4.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->AutoViz) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->AutoViz) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py->panel>=1.4.0->AutoViz) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->AutoViz) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->AutoViz) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->AutoViz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.4.0->AutoViz) (2026.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->AutoViz) (3.0.3)
Downloading autoviz-0.1.905-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 1.5 MB/s eta 0:00:00
Downloading hvplot-0.12.2-py3-none-any.whl (180 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.6/180.6 kB 4.3 MB/s eta 0:00:00
Downloading pandas_dq-1.29-py3-none-any.whl (29 kB)
Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl (255.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 5.8 MB/s eta 0:00:00
Downloading emoji-2.16.0-py3-none-any.whl (610 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 41.7 MB/s eta 0:00:00
Downloading pyamg-5.3.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 56.6 MB/s eta 0:00:00
Installing collected packages: emoji, xgboost, pyamg, pandas-dq, hvplot, AutoViz
  Attempting uninstall: xgboost
    Found existing installation: xgboost 3.4.1
    Uninstalling xgboost-3.4.1:
      Successfully uninstalled xgboost-3.4.1
Successfully installed AutoViz-0.1.905 emoji-2.16.0 hvplot-0.12.2 pandas-dq-1.29 pyamg-5.3.0 xgboost-1.6.2

In [57]:
#AutoViz Class
import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
data = pd.read_csv("adult.csv")
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data
)

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 24 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Total Number of Scatter Plots = 21
All Plots done
Time to run AutoViz = 22 seconds

 ###################### AUTO VISUALIZATION Completed ########################

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [59]:
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data,
    chart_format="png"
)

Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 24 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Total Number of Scatter Plots = 21
All Plots done
Time to run AutoViz = 10 seconds

 ###################### AUTO VISUALIZATION Completed ########################

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [60]:
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data,
    chart_format="html"
)

Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

Saving scatterplots in HTML format
  0%|          | 0/6 [00:00<?, ?it/s]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

 17%|█▋        | 1/6 [00:02<00:11,  2.29s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

 33%|███▎      | 2/6 [00:04<00:08,  2.21s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

 50%|█████     | 3/6 [00:06<00:06,  2.19s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

 67%|██████▋   | 4/6 [00:10<00:05,  2.90s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

 83%|████████▎ | 5/6 [00:12<00:02,  2.66s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='6e2a9ffa-1aa8-4cea-be57-9f93f61d8131', ...)

Saving pair_scatters in HTML format

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='7a4442e3-7452-4b5f-8fd2-296332bcecb3', ...)

Saving distplots_cats in HTML format

Saving distplots_nums in HTML format

KDE plot is erroring due to problems with DynamicMaps. Hence it is skipped

Saving violinplots in HTML format

No date vars could be found in data set

Saving heatmaps in HTML format

Saving cat_var_plots in HTML format

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='db4ac033-bc24-4bec-b743-9575e7040170', ...)

Time to run AutoViz (in seconds) = 221

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K